version: '3.4'

services:
  portfolio.web:
    image: ${DOCKER_REGISTRY-}portfolio
    build:
      context: .
      dockerfile: src/Portfolio.Web/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"